print('='*40)
print('welcome to my python program')
print('='*40)
name= input('what is your name?')
age = input('how old are you?')
favorite_color = input('what is your favorite color?')
print('\n'+'+'*40)
print(f'Hello,{name}')
print(f'you are {age}years old')
print(f'favorite color {favorite_color}.')
print('='*40)